---
language: node_js
node_js:
  - "0.12"
  - "iojs"

matrix:
  fast_finish: true

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"
  - wget http://launchpadlibrarian.net/137699828/libc6_2.17-0ubuntu5_amd64.deb
  - sudo dpkg -i libc6_2.17-0ubuntu5_amd64.deb

install:
  - npm install

script:
  - npm test
